services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MatchUp
    volumes:
      - "MatchUp:/var/lib/postgres/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      
  backend_matchup:
    build: ./
    ports: 
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  MatchUp: